id: PA8690EEB
initial_creation_type: input
source_metadata:
  title: Orgyen Lingpa Series
  language: en
  description: 'Texts by the famous treasure revealer Orgyen Lingpa (o rgyan gling
    pa, b. 1323):'
  volume:
    90b2c950c32245f08596923bbd972273:
      title: A Concise History of Orgyen Padma’s Enlightened Deeds
      parent: History
created_at: '2022-03-01T01:07:17.413249'
last_modified_at: '2022-03-01T01:07:17.413255'
